### ISSUE TITLE
Preparation for Eastern Town Hall Indonesian Break Out Room for 23 April 2022

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#147]
**Tasks:**

- [x] Discussion for what we will do for Indonesian break out room on Saturday, 23 April 2022
- [x] Team meeting on Friday, 22 April 2022. GitHub link: https://github.com/cardano-indonesia/cardano-indonesia-operations/issues/35
- [x] Prepare for the presentation or workshop
- [x] Inform about the meetup in Cardano Indonesia Community social media
