### ISSUE TITLE
Operations [Renumeration]: Workout Q2 March/April Task Compensation

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#152]
Workout a structure for doing the task-based compensation using March/April activity and a means for doing that. 

- [x] Consolidate all the different approaches to reporting team member activity.
- [x] Organise Issues creating any Issue Templates for common activity
- [x] Size the tasks.
- [x] Aggregate the task sizes and any attribution to individuals that worked on a task, apporting the effort.
- [x] Assign a set of points to task sizes (Tee Shirt Size to points) and calaculate total points for each individual.
- [x] Calculate the amounts to be paid
- [x] Confirm the results with the team
- [x] Execute the payments and document (in a separate issue.) 

## Background

See #136 for the motivation and plan. Team members have been asked to capture there activies via Github or a spreadsheet as a starting point. The information provided by the teams can then be assessed and some initial templates, labels and structure established. From these tasks a simple forumlate will be followed.

@zicozibu has developed an [example spreadsheet](https://docs.google.com/spreadsheets/d/1M0oAVvJcGAc5eyc2K9LYSP0BnKoUmCb3QHY7DQC4Bik/edit#gid=0) that covers the ideas for the calculations.

Other material has been provided as Github Issues with different structures, spreadsheets, and documents. The aim of this task is to consolidate the work and derive som Github Issue templates for organising the work. 

The final set of tasks for March/April 2002 (the first interation of this compensation structure) [can be found here](https://docs.google.com/spreadsheets/d/1SHc84F-JPSyUSeylJ-JcfnxtqNUbYUZ0vNE97JF4g0c/edit#gid=0). The execution of the payments is documented in issue #193. 

### Scope

The aim is to account for and reward inidividual team member effort. Only task-based issues are to be considered. Modification or creation of issue template, modifications to repository labels, and task organisation are to be considered. 

Attendence of the weekly team meetings, and hosting the Eastern Townhall events, and any task planning meetings are not to be considered.
