### ISSUE TITLE
Catalyst [Challenge Team]: Attending Challenge Team Roundtable 5 meeting

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#171]
**Tasks:**

- [x] Attend the Roundtable 5 on Friday, 06 May 2022
- [x] Check this [Fund8 Challenge Teams & Onboarding Guidance](https://docs.google.com/document/d/1lmlrqrTthz1CjCj2zNtY7hlAfGsKui_cXIUNygLPsm0/edit)
- [x] Find two available 1.5 hours slot during 18-24 May 2022 for Proof of Life meetings
- [x] Fill this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfKrCwNypGi9vT5rCy2eaHKpe-PbKokFp7nftY_OuzhQmxSrg/viewform) for the slot that you want
- [x] Confirmed at least two members of the CT will take part in the Proof of Life meetings
- [x] [Miro board](https://miro.com/app/board/uXjVO4r7A_c=/)

**Comment by YanTirta** [comment]
Pardon @wolstaeb , since there are some boxes that need to be ticked completed _(either due to the date execution or just not being done yet)_ I will reopen this issue. If there's no objection after this comment I will do so.

**Comment by YanTirta** [comment]
Since there is no objection. I will now reopen this issue.

**Comment by andreassosilo** [comment]
Of course, we need to finish the sub-tasks first before we closed it. Thanks for opening it again @YanTirta .

**Comment by wolstaeb** [comment]
Oops. I'm being a little to aggressive tiding things up as I work on the task compensations.

**Comment by Linh-LP** [comment]
https://discord.com/channels/868850218995707914/944330205923794964

**Comment by andreassosilo** [comment]
Done. Closed
