### ISSUE TITLE
Event [Townhall]: Preparation for Indonesia Break Out Room for 26 March 2022

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#179]
**Tasks:**

- [x] Discussion about the topics to cover during meetup/workshop
- [x] Preparation for the presentation
- [x] Inform in the Telegram & Discord group
- [x] Double check the link for Zoom meeting

**Comment by andreassosilo** [comment]
Done. Closed
