### ISSUE TITLE
Catalyst [Reporting]: Attending Fund 8 Onboarding Session A for Eastern Catalyst School proposal

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#181]
**Tasks:**

- [x] Attending Fund8 Onboarding Session A on Tuesday, 17 May 2022 at 09:00-10:00 UTC
- [x] Get information for Catalyst Coordinator
- [x] Onboarding Guidance: https://bit.ly/F8-Onboarding-Guidance 
- [x] Proof of Life Meetings & Office Hours + Contacts: https://bit.ly/F8-PoL-Schedule
- [x] [Fund 8 Onboarding slides](https://docs.google.com/presentation/d/1zzc6s1BitM_nQ7yQ-OSpbAzf7jWUk8-NpbOs6kjRWDM)
- [x] Monthly Progress Report Output: https://bit.ly/Funded-Projects-Reports
- [x] Monthly Funds Distribution Calendar: https://bit.ly/Funds-Distr-Cal

**Comment by zicozibu** [comment]
@Mietran0407 and @zicozibu is also attending

**Comment by andreassosilo** [comment]
Done. Closed
