### ISSUE TITLE
Catalyst [Reporting]: Attending Proof of Life Session on New Member Onboarding Category

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#184]
**Tasks:**

- [x] Attending Proof of Life session on New Member Onboarding category challenge on Friday, 20 May 2022 at 17:00-19:00 UTC
- [x] Meeting link: https://meet.google.com/cpc-kdrw-ook
- [x] Give presentation about "F8: Eastern Catalyst School" with the Challenge Team & other funded proposers
- [x] Project ID for F8: Eastern Catalyst School -> 800171

**Comment by andreassosilo** [comment]
Done. I presented this proposal on the New Member Onboarding category challenge.
