### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 1st workshop in Indonesia break out room 21 May 2022

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#185]
**Tasks:**

- [x] Prepare material for F9: Introduction to Catalyst in Indonesian language -> [Link Document](https://docs.google.com/presentation/d/1EuWFoqFOPKZ4KKkfxxhegjV0wjpOeoA8ojJZW5K596Y/edit?usp=sharing) by @syarbel 
- [x] Promotion & marketing to the Indonesian community via Cardano Forum, Telegram, Discord, Twitter, etc.
- [x] Creating flyer for this workshop by @YanTirta 
- [x] Discussion on Friday, 20 May 2022 at Core Team Cardano Indonesia Meeting. See [minutes of meeting (MoM)](https://github.com/cardano-indonesia/cardano-indonesia-operations/issues/37) by @andreassosilo 
- [x] Create & discuss rundown for the workshop

**Comment by syarbel** [comment]
Adding gdoc link for F9: Introduction to Catalyst in Indonesian language. Indonesian ECS members already given access to edit the powerpoint.

**Comment by andreassosilo** [comment]
Preparation done. Issue closed.
