### ISSUE TITLE
Workshop [Eastern Catalyst School]: Give 1st workshop "F9: Introduction to Catalyst" in Indonesian language

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#186]
**Tasks:**

- [x] Give 1st workshop: "Introduction to Catalyst" in the Indonesian break out room
- [x] Hosts: Andreas & Yan
- [x] Speakers: Dani & Andy 
- [x] Material (in Indonesian): please provide [link to Google Drive here](https://docs.google.com/presentation/d/1EuWFoqFOPKZ4KKkfxxhegjV0wjpOeoA8ojJZW5K596Y/edit?usp=sharing)
- [x] Create a summary for the workshop after that

**Summary:** [Link to workshop summary on Cardano Forum Indonesia](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-1-introduction-to-catalyst-recap/101649?u=danivideda)

**Comment by syarbel** [comment]
Adding PPT material link for Introduction to Catalyst in Indonesian language. Indonesian ECS members already given access to edit the powerpoint.

**Comment by danivideda** [comment]
- Checked tasks for completing the workshop
- In progress for summary on Cardano Forum

**Comment by danivideda** [comment]
* Summary link added
* Done

**Comment by zicozibu** [comment]
- Recording is encoded, trimmed, and uploaded to Google Drive to be uploaded by @Mietran0407 to ETH Youtube channel

Video link: https://drive.google.com/file/d/1lWixKmqdFNP0n-8vnwSmEs8pjJsfsrxL/view
Title: Eastern Town Hall - Indonesia Break Out Room - Eastern Catalyst School #1 (please change if this not okay)
Thumbnail: https://drive.google.com/file/d/1ImyRrlreUO4uR07h9o8ey9sZsf2gqvb2/view (please change if you have a better idea)

**Comment by Mietran0407** [comment]
Hi @zicozibu, I have uploaded it on Youtube. The thumbnail link requires access permission, you can update it and I will put it on the video later.
Here is the YT link: https://youtu.be/In-XesiQ7Pw
