### ISSUE TITLE
Workshop [Project Management]: Scheduling Event for ECS Indonesia Workshops in Fund 9

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#189]
**Tasks:**

- [x] Plan the schedule for 6x workshops in Fund 9 in Core Team Eastern Catalyst School Indonesia Telegram
- [x] Coordinating host, co-host and speaker for 6x workshops
- [x] Gathering needed materials to make presentations
- [x] Assign tasks/issues to the Eastern Catalyst School Team Member

**Comment by andreassosilo** [comment]
Done. Closed.
