### ISSUE TITLE
Catalyst [Reporting]: Submit KPI Report May 2022 for Fund 8

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#190]
**Tasks:**

- [x] Filling the Google Forms for May 2022 report for F8: Eastern Catalyst School. Deadline: 24 May 2022.
- [x] Submission of the [Catalyst Monthly Report](https://bit.ly/CatalystMonthlyReport)
- [x] Gather the necessary information to fill the KPI report for May 2022 from ECS Indonesia, ECS Japan, ECS Vietnam activities.
- [x] Inform in the Eastern Town Hall Core Team Meeting

**Comment by andreassosilo** [comment]
Done. Submitted on 23 May 2022. Evidence could be seen on eastern.townhall@gmail.com
