### ISSUE TITLE
Catalyst [Challenge Team]: Host 2nd Proof of Life Meeting for F8: Grow East Asia, Grow Cardano

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#195]
**Tasks:**

- [x] Inform schedule in Telegram
- [x] Contacting funded proposers, who has not doing Proof of Life
- [x] Prepare link & material
- [x] Host the 2nd Proof of Life on Sunday, 22 May 2022 at 13:00-14:00 UTC
- [x] Record the PoL on cloud

**Comment by andreassosilo** [comment]
Done. We did the 2nd Proof of Life meeting for F8: Grow East Asia, Grow Cardano.

**Comment by zicozibu** [comment]
There are 4 proposals scheduled, 3 of them showed up, only 1 (due to multiple proposals, probably already done it in the other Challenge Team)

**Comment by zicozibu** [comment]
@YanTirta provided script to guide the scheduled proposers to give PoL in the CT Telegram Group:
---
📌 To provide the most smoothest experience to the following 2nd PoL Meeting participants : 

We have provided you a script to read out during our 2nd PoL Meeting. In that script your ID has also been provided. 

You would need to still provide us :
1. Your name
2. Primary place of business
3. Intended completion date

📌 In alphabetical order :
1. Bringing E.A Investors to Cardano | @Lucasmac_TA 
https://docs.google.com/document/d/1i4mcv615YQX_6wemD3s2Shj7z9oKMvLUah7wiPLbglw/edit?usp=sharing

2. Cardano Forest In Vietnam | @quocnguyen87 
https://docs.google.com/document/d/1kE8gJFjwT_lioNT-P4A8nJnXR5UcgdbWNehxLxmMhCY/edit?usp=sharing

3. Duo - Filipino Gameplay | @aussiegingersnap
https://docs.google.com/document/d/1MENW2yUsmAS4BwfquAcS7vFY542G4HIr6SOGT5FaMFA/edit?usp=sharing

4. Storytelling using Mighty Cardano | @BionicPinky
https://docs.google.com/document/d/18HzspQjZgYyea6y8nlaqu2obTmJWhyWWY0lMd9xjI_M/edit?usp=sharing
---

**Comment by zicozibu** [comment]
@YanTirta provided script to guide the scheduled proposers to give PoL in the CT Telegram Group:
---
📌 To provide the most smoothest experience to the following 2nd PoL Meeting participants : 

We have provided you a script to read out during our 2nd PoL Meeting. In that script your ID has also been provided. 

You would need to still provide us :
1. Your name
2. Primary place of business
3. Intended completion date

📌 In alphabetical order :
1. Bringing E.A Investors to Cardano | @Lucasmac_TA 
https://docs.google.com/document/d/1i4mcv615YQX_6wemD3s2Shj7z9oKMvLUah7wiPLbglw/edit?usp=sharing

2. Cardano Forest In Vietnam | @quocnguyen87 
https://docs.google.com/document/d/1kE8gJFjwT_lioNT-P4A8nJnXR5UcgdbWNehxLxmMhCY/edit?usp=sharing

3. Duo - Filipino Gameplay | @aussiegingersnap
https://docs.google.com/document/d/1MENW2yUsmAS4BwfquAcS7vFY542G4HIr6SOGT5FaMFA/edit?usp=sharing

4. Storytelling using Mighty Cardano | @BionicPinky
https://docs.google.com/document/d/18HzspQjZgYyea6y8nlaqu2obTmJWhyWWY0lMd9xjI_M/edit?usp=sharing
---
