### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 2nd workshop in Indonesia breakout room

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#210]
## Preparation for 2nd workshop: "How to become proposer in Catalyst Fund 9 – Part 1"

Eastern Catalyst School - Indonesia Team log line
- [Previous Log](https://github.com/C3ETH/c3eth-operations/issues/186) 
- [Next Log
](https://github.com/C3ETH/c3eth-operations/issues/221)

**Tasks:**

- [x] Meeting on Thursday, 02 June 2022 for Eastern Catalyst School Indonesia
- [x] 2nd Workshop material preparation @syarbel [[PPT Link](https://docs.google.com/presentation/d/1SQmnsXcUGxIMXDeYoA3bgntIOG0nJzzhkOi-8R3Dki0/edit?usp=sharing)] 
- [x] Create flyer @YanTirta 
- [x] Share workshop information on social media and groups (Twitter, Discord, Telegram)
- [x] Record the event to cloud storage @zicozibu 
- [x] Upload workshop recording to YouTube @zicozibu  [Youtube Link](https://youtu.be/_Eictorz3pU)
- [x] Create a recap workshop in Cardano Indonesia Forum (screenshots, participants, etc.) by @andreassosilo 

### Workshop preparation

1. Speaker: @syarbel @andreassosilo 
2. Moderator: Ayu Kusumaningtyas
3. Host: @andreassosilo @zicozibu 
4. Things to cover:

    

    **Part 1 Materials**

    - Timeline for Fund 9 → 10 minutes
    - Introduction to Fund 9 categories (todo: check categories) → 20 minutes
    - Introduction to proposer role in Catalyst → 5 minutes
    - How to submit a proposal on Ideascale (register, submission form) → 15 minutes
    - Q&A → 10 minutes
    - Explaining impact → 20 minutes 
    - Explaining feasibility, and auditability (only preview) → 10 minutes
    - Inform Catalyst School 1-on-1 Session Request → [Form](https://forms.gle/eXjcsTXLqG28UTey5)
    - Q&A -> 20 minutes

    
    **Part 2 Materials** _~to be discuss in next meeting_

    - Explaining feasibility → 15 minutes
    - Explaining auditability → 15 minutes
    - Share a good example of a previous proposal (e.g CI Workshop from F7)
    - How to flag PAs assessment
    - Tips for a good proposal presentation
    - How to promote your proposal to gain votes (show results from Fund 8, IdeaFest Reels)

5. ETH opening refinement for Indonesia

### Next meeting [link](https://github.com/C3ETH/c3eth-operations/issues/227)
1. Project management -> discuss workshop compensation structure
2. Follow up on Linh's idea on new session structures (different levels for each workshop: beginner, intermediate, an expert in the blockchain)
3. Website creation for ECS, who will create and maintain it

**Comment by danivideda** [comment]
Update: flyer and info already shared on Telegram, Discord, and Twitter

**Comment by syarbel** [comment]
Add 1-on-1 Session Request Form to Part 1 materials
Add note for Part 2 Materials that will be discuss in next meeting (since Part 2 will be next Workshop on June 18th)

**Comment by andreassosilo** [comment]
Recap done. See #212

**Comment by zicozibu** [comment]
Recording is uploaded to Youtube at https://youtu.be/_Eictorz3pU

**Comment by zicozibu** [comment]
Link to the next meeting is added at https://github.com/C3ETH/c3eth-operations/issues/227
