### ISSUE TITLE
Workshop [Eastern Catalyst School]: Give 2nd workshop: "F9: How to Submit Proposal - Part 1" in Indonesian language

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#211]
**Tasks:**

- [x] Give 2nd workshop: "F9: How to Submit Proposal - Part 1" in the Indonesian break out room
- [x] Hosts: @zicozibu 
- [x] Speakers: @syarbel & @@andreassosilo 
- [x] Flyer by @YanTirta 
- [x] Material (in Indonesian) by @syarbel : please provide [link to Google Drive here](https://docs.google.com/presentation/d/1SQmnsXcUGxIMXDeYoA3bgntIOG0nJzzhkOi-8R3Dki0/edit#slide=id.g131173dd4b1_0_49)
- [x] Create a summary for the workshop after that by @andreassosilo #212 

**Summary:** [Link to workshop summary on Cardano Forum Indonesia](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-1-introduction-to-catalyst-recap/101649?u=danivideda)

**Comment by andreassosilo** [comment]
Done. Closed.



![Image](https://user-images.githubusercontent.com/50327438/172216028-2a016934-a6da-4793-93cd-9cff59a70f76.jpg)
