### ISSUE TITLE
Community [Community Moderation]: Setup Bot & Command for Eastern Town Hall Indonesia Telegram

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#217]
**Tasks:**

- [x] Learning how to setup [Rose bot](https://missrose.org/guide/getting-started/adding-rose/) in Telegram
- [x] Adding Rose to [Eastern Town Hall Indonesia Telegram Group]()
- [x] Setup anti-flood, filters, captcha, bans, mute, kick, greetings, etc.
- [x] Testing

**Comment by andreassosilo** [comment]
Done. Closed.
