### ISSUE TITLE
Catalyst [Project Management]: Scheduling 1-on-1 session for Indonesian community

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#220]
**Tasks:**

- [x] Create email template to be sent to the requester of 1-on-1 support in Indonesian language
- [x] Translate [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSd9bos5DmVtKYRCR29xjVZvVr7QO43UrPbhrOzxITH_iYnTlA/viewform) from Catalyst School
- [x] Send email to the 1-on-1 session requester

**Comment by syarbel** [comment]
Created 2 e-mail response templates for:
1. Mentor have been assigned to run a 1 on 1 session ✅
2. No Mentor available for session ✅

available on indonesia.ecs@gmail.com
ECS Indonesia Core Team already have an access to Gmail Account.

**Comment by syarbel** [comment]
Translated and added Bahasa Indonesia section to Catalyst School's [Feedback Form](https://forms.gle/cfTnrJAHBgDsanzQ9). ✅

**Comment by syarbel** [comment]
Email response already sent to 6 session requests in Bahasa Indonesia.
The defined mentor will need to contact the requesters to agree on a schedule for running the session.

**Comment by andreassosilo** [comment]
Done. Closed.
