### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 3rd workshop in Indonesia break out room 18 June 2022

### ISSUE THREAD

**Issue by zicozibu** [C3ETH/c3eth-operations#221]
## Preparation for 3rd workshop: "How to become proposer in Catalyst Fund 9 – Part 2" 18 June 2022

Eastern Catalyst School - Indonesia Team log line
- [Previous Log 
](https://github.com/C3ETH/c3eth-operations/issues/210)
- [Next Log
](https://github.com/C3ETH/c3eth-operations/issues/243)

**Tasks:**

- [x] Meeting on Thursday, 09 June 2022 for Eastern Catalyst School Indonesia ([meeting notes](https://github.com/C3ETH/c3eth-operations/issues/227))
- [x] Meeting on Thursday, 16 June 2022 for Eastern Catalyst School Indonesia
- [x] 3rd Workshop material preparation @syarbel [[PPT Link](https://docs.google.com/presentation/d/15GhwSkgRFWO9gVgsIEbSJQ9onGzO3_LrDl9HG6W7jRI/edit#slide=id.g133368a0cfc_0_548)] 
- [x] Create flyer @YanTirta 
- [x] Share workshop information on social media and groups (Twitter, Discord , Telegram OK, SPO Cardanesia, SPO Kawan)
- [x] Record the event to local storage @zicozibu 
- [x] Upload workshop recording to YouTube @zicozibu [Youtube link](https://youtu.be/WhLOGmXJPCo)
- [x] Create [a recap workshop](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-3-how-to-submit-proposal-in-catalyst-part-2-recap/103537/2) in Cardano Indonesia Forum (screenshots, participants, etc.) by @andreassosilo 
- [x] Translate 1-on-1 Feedback Form at [link](https://docs.google.com/forms/d/e/1FAIpQLSd9bos5DmVtKYRCR29xjVZvVr7QO43UrPbhrOzxITH_iYnTlA/viewform?fbzx=4522461197136757668) @syarbel 

### Workshop preparation

1. Speaker: @danivideda @andreassosilo 
2. Moderator: Dewi Gunarto (need to be invited next meeting 16 June) 
3. Host: @andreassosilo @zicozibu 
4. Things to cover:
        
    **Part 2 Materials** _~
    - 1st Session: @danivideda 
    - Explaining feasibility → 10 minutes 
    - Explaining auditability → 10 minutes
    - Share a good example of a previous proposal (e.g Eastern Catalyst School from FP Fund8) -> 10 minutes
    - How to flag PAs assessment -> 10 minutes [link](https://docs.google.com/spreadsheets/d/1hHp4YTEvEuOtXHZzlGESBx-UtOtd9pxjbXWXzDpyY6I/edit#gid=2132956759)
    - Q&A #1 -> 5 minutes
    - 2nd Session: @andreassosilo 
    - Tips for a good proposal presentation -> 20 minutes 
    - How to promote your proposal to gain votes (show results from Fund 8, IdeaFest Reels) -> 20 minutes
    - Q&A #2 -> 5 minutes

5. ETH opening refinement for Indonesia: template for Dewi Gunarto (for main Room) --> look into earlier PPT 

6. Project management -> discuss workshop compensation structure
    - WORKSHOP
    - Per Workshop = USD 4320 / 12 workshops in 2 funds = USD 360 / workshop
    - Speaker:  USD 60/hour x 2 = USD 120
    - Moderator: USD 30/hour x 2= USD 60
    - Host: USD 30/hour x 2 = USD 60
    - Remaining: USD 120
    - 
    - EDUCATION MATERIAL
    - Per Workshop = USD 1250 / 12 workshops in 2 funds = USD 104.16 / workshop
    - PPT = USD 60 (TBD)
    - Recording + Upload to Youtube (timestamping, description, thumbnails): USD 30 / recording
    - Short Feed (Instagram, etc.) = USD 14.16 / feed

    - MARKETING
    - Per Workshop = USD 1250 / 12 workshops in 2 funds = USD 104.16 / workshop
    - Flyer: USD 30 (TBD) @YanTirta 
    - Rewards/Doorprize: USD 74.16 (including transaction fees)
    - 
    - 1-ON-1 SESSION
    - Per Fund = USD 600 / 2 funds = USD 300 / fund
    - First come first serve 
    - USD 30 / 30-minutes session (TBD)
    - Can be grouped by same topic request 
    - Request Form needs to be made
    - After finishing, requester need to fill the Feedback Form at [link](https://docs.google.com/forms/d/e/1FAIpQLSd9bos5DmVtKYRCR29xjVZvVr7QO43UrPbhrOzxITH_iYnTlA/viewform?fbzx=4522461197136757668)
    - 
    - WEBSITE
    - TBD with @YanTirta 
    - 
    - PROJECT MANAGEMENT
    - TBD, might use T-Shirt Size 

7.  Resources organization (E-mail, etc.)
    - Email (Google Drive):  ecs.indonesia@gmail.com @syarbel ✅
    - Email changed into: indonesia.ecs@gmail.com
    - ADA Handle: $ecs.indonesia @danivideda --> please create GitHub issue
    - ADA Handle changed into: indonesia.ecs@gmail.com 
    - Wallet: @danivideda together with @syarbel

### 1-on-1 Session Discussion
1. Budget
2. Email response template ✅
3. Facilitator/Mentor: currently there are 5 requests (facilitators already defined) ✅
- Fiter (by @zicozibu) : DONE
- Ivan Kwananda (by @andreassosilo): DONE
- Nur Wahyogi - proposer (by @andreassosilo): next week
- Nur Wahyogi - PA (by @syarbel): next week
- Gorga - Proposer (by @zicozibu): need to contact 
- Andre Tuwan - Propose (by @zicozibu); need to contact

5. Request form to be used: [form](https://docs.google.com/forms/d/e/1FAIpQLSd9zvxtLtXKEcYEJas6Idj1YmA2kGyK27mIR-38eWITPUhHZw/viewform)

### Next meeting [link]
1. Website creation for ECS, who will create and maintain it
2. Follow up on Linh's idea on new session structures (different levels for each workshop: beginner, intermediate, an expert in the blockchain)
3. Discussion with Japanese and Vietnam Team @zicozibu @YanTirta

**Comment by syarbel** [comment]
Created indonesia.ecs@gmail.com for storing material & ppt ✅
Migrate files from individual G-Drive to Indonesia ECS' G-Drive ✅
Give access to all Indonesian ECS Core Team ✅

**Comment by syarbel** [comment]
Created 2 e-mail response templates for:
1. Mentor have been assigned to run a 1 on 1 session ✅
2. No Mentor available for session ✅

**Comment by zicozibu** [comment]
On 5.

Script suggestion:

====

Teks untuk Moderator di Main Hall

Selamat sore semua, saya [nama moderator], bagian dari Eastern Town Hall

tentang Eastern Town Hall (part of Project Catalyst)

(ENG aslinya, skip)
Welcome to the Experiment!
Things may:
break
lack documentation
differ greatly between iterations
diorient, overload, and inspire

Our goal: Provide a safe and lively environment for you to explore the highest potential of human collaboration

(ID, yang dibawakan)
Selamat datang ke Eksperimen!
Karena ini adalah sebuah eksperimen, maka wajar jika 
tidak mulus
kurang dokumentasi
jauh berbeda antara iterasinya
mungkin membingungkan, terkadang informasinya terlalu banyak, tapi semoga bisa menginspirasi

Tujuan kami adalah menyediakan sebuah wadah yang aman dan nyaman untuk kita semua menjelajahi potensi tertinggi dari kerjasama antara manusia


Invitation to Indonesian Break Out Room
Setelah Main Room ini, nanti kita akan ada Break Out Room khusus dalam Bahasa Indonesia, yang hari ini agendanya adalah:

Eastern Catalyst School - Indonesia
Workshop 3 - Menjadi Proposer bagian 2

Silakan bergabung, atau bebas juga jika ingin bergabung di Break Out Room yang lainnya.
===

**Comment by zicozibu** [comment]
Workshop recording has been uploaded to Youtube at https://youtu.be/WhLOGmXJPCo

**Comment by syarbel** [comment]
Workshop Recap has been created and added to the checklist.
I will close this issue.
