### ISSUE TITLE
Workshop [Eastern Catalyst School]: 1-on-1 session "Proposing in Catalyst" in Indonesian language

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#223]
**Tasks:**

- [x] Reach out to the student
- [x] Schedule a 1-on-1 session with the student
- [x] Host the conference call with the student
- [x] Share and ask the student to fill the [feedback form](https://forms.gle/juMT5ZtKsmdUW95g9)
- [x] Update the Google Sheet from Catalyst School
- [x] Update task in [Dework](https://app.dework.xyz/catalyst-swarm/catalyst-school-task?taskId=aab37bc4-2a36-4c4b-8ecd-f77726a66a72)

**Comment by andreassosilo** [comment]
1-on-1 session with Ivan Kwananda in Indonesian language is done.
