### ISSUE TITLE
Catalyst [Reporting]: Catalyst Coordinator Meeting 14 June 2022

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#224]
**Tasks:**

- [x] Attending Catalyst Coordinator Meeting on Tuesday, 14 June 2022
- [x] Presenting the progress of our funded proposal F8: Eastern Catalyst School in the break out room
- [x] Get the [Catalyst Coordinator Meeting Presentation Slide](https://docs.google.com/presentation/d/1ZOeYiw9HN1QPpBmGv3js8tp0GOH397NWtuAl0_f5FAI/edit#slide=id.gb756fa1b15_0_0)

**Comment by andreassosilo** [comment]
Done. Closed.
