### ISSUE TITLE
Meeting [Eastern Catalyst School]: ECS Indonesia Weekly 9 June 2022

### ISSUE THREAD

**Issue by danivideda** [C3ETH/c3eth-operations#227]
## Topics

1. Discuss #221
2. Eastern Catalyst School further break downs regarding budget, roles, and 1-on-1 session

## Meeting Details:

- Last Meeting: TBD
- Next Meeting: TBD

### Attendees:
- Andy @zicozibu 
- Dani @danivideda
- Syarbel @syarbel 
- Andreas @andreassosilo 
- Yan @YanTirta  

### Apologies
All present

### Tasks
- [x] Translate 1-on-1 Feedback Form at [link](https://docs.google.com/forms/d/e/1FAIpQLSd9bos5DmVtKYRCR29xjVZvVr7QO43UrPbhrOzxITH_iYnTlA/viewform?fbzx=4522461197136757668) @syarbel 
- [x] Email response template @syarbel 
- [x] Email (Google Drive):  ecs.indonesia@gmail.com @syarbel
- [x] ADA Handle: $ecs.indonesia @danivideda 

### Agenda

1. Project management -> discuss workshop compensation structure
    - WORKSHOP
    - Per Workshop = USD 4320 / 12 workshops in 2 funds = USD 360 / workshop
    - Speaker:  USD 60/hour x 2 = USD 120
    - Moderator: USD 30/hour x 2= USD 60
    - Host: USD 30/hour x 2 = USD 60
    - Remaining: USD 120
    - 
    - EDUCATION MATERIAL
    - Per Workshop = USD 1250 / 12 workshops in 2 funds = USD 104.16 / workshop
    - PPT = USD 50
    - Recording + Upload to Youtube (timestamping, description, thumbnails): USD 30 / recording
    - Remaining: USD 14.16

    - MARKETING
    - Per Workshop = USD 1250 / 12 workshops in 2 funds = USD 104.16 / workshop
    - Flyer: USD 15 / flyer @YanTirta 
    - Rewards/Doorprize: USD 74.16 (including transaction fees)
    - Remaining: 15 USD -> going to $indonesia.ecs for emergency fund
    - 
    - 1-ON-1 SESSION
    - Per Fund = USD 600 / 2 funds = USD 300 / fund
    - First come first serve 
    - USD 30 / 30-minutes session (TBD)
    - Can be grouped by same topic request 
    - Request Form needs to be made
    - After finishing, requester need to fill the Feedback Form at [link](https://docs.google.com/forms/d/e/1FAIpQLSd9bos5DmVtKYRCR29xjVZvVr7QO43UrPbhrOzxITH_iYnTlA/viewform?fbzx=4522461197136757668)
    - 
    - WEBSITE
    - TBD with @YanTirta 
    - 
    - PROJECT MANAGEMENT
    - TBD, might use T-Shirt Size 

2.  Resources organization (E-mail, etc.)
    - Email (Google Drive):  ecs.indonesia@gmail.com @syarbel ✅
    - ADA Handle: $ecs.indonesia @danivideda 

### 1-on-1 Session Discussion
1. Budget
2. Email response template ✅
3. Facilitator/Mentor: currently there are 5 requests (facilitators already defined) ✅
4. Request form to be used: [form](https://docs.google.com/forms/d/e/1FAIpQLSd9zvxtLtXKEcYEJas6Idj1YmA2kGyK27mIR-38eWITPUhHZw/viewform)

### Next meeting footnotes
1. Website creation for ECS, who will create and maintain it
2. Follow up on Linh's idea on new session structures (different levels for each workshop: beginner, intermediate, an expert in the blockchain)
3. Discussion with Japanese and Vietnam Team @zicozibu @YanTirta 

### Discussion Summary:
-

**Comment by zicozibu** [comment]
Meeting Notes between @YanTirta and Simon from Catalyst School
- There is additional budget from Fund6 proposal (https://cardano.ideascale.com/c/idea/369845)
- TBD in a meeting with Victor, Simon, @andreassosilo @YanTirta @zicozibu 

Meeting Notes on ETH 13 June 2022 on Eastern Catalyst School:
- Eastern Catalyst School will have its own budget
- Fixed compensation on several parts (workshop, 1-on-1, educational material, marketing)
- Variable compensation (t-shirt size) on others (project management, website)
- Payment based on first-in-first-out (in the order of received fund sequence)

Funding in June 2022 (13th June): https://docs.google.com/spreadsheets/d/1bfnWFa94Y7Zj0G7dtpo9W1nAYGovJbswipxiHT4UE3g/edit#gid=793243167
$ 6815/27260 with IOG conversion rate 0.458 USD/ADA worth ADA 14879.9126638
