### ISSUE TITLE
Workshop [Eastern Catalyst School]: Prepare 1st workshop in Vietnam on June 12th 2022 - Sunday Session

### ISSUE THREAD

**Issue by Mietran0407** [C3ETH/c3eth-operations#238]
## Preparation for 1st workshop on June 12th 

**Tasks:**
- [x] Prepare the registration form and send it out to the community - [registration form](https://forms.gle/t6noPpkH884g5UUW7?fbclid=IwAR3xklmW_4hsmf7xn9PLUFqjDoqFWjYkO7HdAZjaR3K-miyAhoHLsDOYZoM)
- [x] Create Flyer
- [x] Arrange 2 groups, inform and add them to the GG classroom
- [x] Prepare documentation
- [x] Upload Documentation
- [x] Follow up and Remind the attendees
- [x] Record the meeting
