### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 4th Workshop: "How to become Proposal Assessor (PA) in Catalyst Fund 9" 02 July 2022

### ISSUE THREAD

**Issue by zicozibu** [C3ETH/c3eth-operations#243]
## Preparation for 4th Workshop: "How to become Proposal Assessor (PA) in Catalyst Fund 9" 2 July 2022

Eastern Catalyst School - Indonesia Team log line
- [Previous Log 
](https://github.com/C3ETH/c3eth-operations/issues/221)
- [Next Log](https://github.com/C3ETH/c3eth-operations/issues/307)

**Tasks:**

- [x] Meeting on Thursday, 30 June 2022 for Eastern Catalyst School Indonesia
- [x] 4th Workshop material preparation @syarbel [[PPT Link](https://docs.google.com/presentation/d/1CquwAjh4UGaLKc_1er4wtQxvKvMf5Hnuv2TJjARF1x0)] 
- [x] Create flyer @YanTirta 
- [x] Share workshop information on social media and groups (Twitter, Discord, Telegram OK, SPO Cardanesia, SPO Kawan)
- [x] Record the event to local storage @zicozibu 
- [x] Upload workshop recording to YouTube @zicozibu [YouTube Link](https://www.youtube.com/watch?v=GlQGqqxPGXo)
- [x] Create [a recap workshop](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-4-how-to-become-a-proposal-assessor-recap/104407) in Cardano Indonesia Forum (screenshots, participants, etc.) by @syarbel  

### Workshop preparation

1. Speaker: @syarbel @zicozibu 
2. Moderator: Dewi Gunarto
3. Host: @andreassosilo @zicozibu 
4. Things to cover:
    - Opening introduction -> 5 min
    - Fund 9 overview -> 5 min
    - PA roles introduction -> 5 min
    - How to register PA in IdeaScale -> 5 min
    - Q&A part 1 -> 10 min (max)
    - General PA workflow (using CA tools, Notion, Excell) -> 30 minutes
    - How to give good and excellent assessment [Fund 9 PA Guide](https://docs.google.com/document/d/1g-iZhDlKhUBZkui1uv8NVNfJC4oVD3JtR-P6Fue7XPU/edit?usp=sharing) -> 15 minutes
    - Sharing session and Q&A: Tips for PAs -> 15 minutes
        - Learn the challenge category that you understand
        - Don't be subjective when assessing the proposal
        - Googling for answers to back your arguments or reasoning
    - Closing -> 10 minutes
        - Indonesian proposals
        - Eastern Town Hall proposals

### Proposals
**Indonesia**
- https://cardano.ideascale.com/c/idea/417366 -> Andre Elausta  
- https://cardano.ideascale.com/c/idea/416801 -> Ivan Kwananda  
- https://cardano.ideascale.com/c/idea/416344 -> Fanny Wijaya  
- https://cardano.ideascale.com/c/idea/417704 -> Lutvi Rosyady 
- https://cardano.ideascale.com/c/idea/418728 -> Gorga Siagian
- https://cardano.ideascale.com/c/idea/420823 -> Sonny Dhamayana

**Eastern Town Hall**
- Eastern Town Hall Team Operation - https://cardano.ideascale.com/c/idea/417263 
- Onboarding East Asia Today - https://cardano.ideascale.com/c/idea/417277
- Connecting Asian Voter & Proposer - https://cardano.ideascale.com/c/idea/417265 
- Asian Stakepool Alliance - https://cardano.ideascale.com/c/idea/421171
- Grow Eastern Hemisphere, Grow Cardano - https://cardano.ideascale.com/c/idea/417316
- Eastern Hemisphere dRep Town Hall - https://cardano.ideascale.com/c/idea/420262

### Next meeting [link]
1. Weekly meeting for vPA workshop

**Comment by zicozibu** [comment]
@syarbel please note on slide 21, CA Tool is already renamed to PA Tool, with the new URL: https://cardanocataly.st/pa-tool/#/

Don't worry though, if you go to CA Tool URL, there is a redirect there now

**Comment by zicozibu** [comment]
Video is uploaded to YouTube on link: https://www.youtube.com/watch?v=GlQGqqxPGXo

**Comment by syarbel** [comment]
Workshop Recap has been created and added to the checklist.
I will close this issue.
