### ISSUE TITLE
Workshop [Eastern Catalyst School]: Prepare 3rd workshop in Vietnam on June 26th 2022 - Sunday Session

### ISSUE THREAD

**Issue by Mietran0407** [C3ETH/c3eth-operations#247]
## Preparation for 3rd workshop on June 26th 

**Tasks:**
- [x] Meeting to prior class
- [x] Prepare documentation
- [x] Upload Documentation
- [x] Follow up and Remind the attendees
- [x] Record the meeting 
- [X] Create [after-class review form](https://docs.google.com/forms/d/e/1FAIpQLSein-mqBPQAL53HMHmAVhotfj750JrINOxpHfHt0pOgGZ8X_A/viewform)
