### ISSUE TITLE
Workshop [Eastern Catalyst School]: Prepare 2nd workshop in Vietnam on June 21st 2022 - Tuesday Session

### ISSUE THREAD

**Issue by Mietran0407** [C3ETH/c3eth-operations#248]
## Preparation for 2nd workshop on June 19th 

**Tasks:**
- [x] Meeting to discuss the next meeting 
- [x] Remind Student to join the 2nd session 
- [x] Prepare documentation
- [x] Upload Documentation
- [x] Follow up and Remind the attendees
- [x] Record the meeting
