### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 5th Workshop: "How to become Veteran Proposal Assessor (vPA) in Catalyst Fund 9" 16 July 2022

### ISSUE THREAD

**Issue by syarbel** [C3ETH/c3eth-operations#307]
## Preparation for 5th Workshop: "How to become Veteran Proposal Assessor (vPA) in Catalyst Fund 9" 16 July 2022

Eastern Catalyst School - Indonesia Team log line
- [Previous Log 
](https://github.com/C3ETH/c3eth-operations/issues/243)
- [Next Log](https://github.com/C3ETH/c3eth-operations/issues/321)

**Tasks:**

- [x] Meeting on Thursday, 14 July 2022 for Eastern Catalyst School Indonesia
- [x] 5th Workshop material preparation @syarbel [[PPT Link](https://docs.google.com/presentation/d/1febYu_FWc2u9gkuiVVdhUR9reyTbEVw0HMmlDGT6Um8/edit?usp=sharing)] 
- [x] Create flyer @YanTirta 
- [x] Share workshop information on social media and groups (Twitter, Discord, Telegram OK, SPO Cardanesia, SPO Kawan)
- [x] Record the event to local storage @zicozibu 
- [x] Upload workshop recording to YouTube @zicozibu YouTube [Link](https://www.youtube.com/watch?v=soTwNaq-dyo)
- [x] Create [a recap workshop](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-5-how-to-become-a-veteran-proposal-assessor-recap/104842) in Cardano Indonesia Forum (screenshots, participants, etc.) @andreassosilo 

### Workshop preparation

1. Speaker: @andreassosilo 
2. Moderator: Dewi Gunarto
3. Host: @zicozibu 
4. Things to cover:
    - Opening introduction -> 5 min
    - Fund 9 overview -> 5 min
    - Q&A part 1 -> 10 min (max)
    - How to flagging (for Proposer) + Q&A -> 15 min
    - vPA Roles introduction -> 30 minutes
    - Sharing session as former Fund 8 vPA and Q&A: Tips for PAs -> 30 minutes
    - Closing -> 5 minutes
