### ISSUE TITLE
Catalyst [Proposal]: Flagging assessment for F10: Grow Eastern Hemisphere, Grow Cardano in Fund 9 - 18 July 2022

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#310]
**Tasks:**

- [x] Read the assessment from PA for Fund 10 Challenge Setting "Grow Eastern Hemisphere, Grow Cardano"
- [x] Give flagging & feedback
- [x] Upload & submit the form

Link: [Fund 9 Eastern Town Hall Proposal Flag](https://docs.google.com/spreadsheets/d/1vfwYy9Vlzc6QD7ttOD5RWevNxShMGNYCKGnswWNxIHs/edit#gid=0)

**Comment by andreassosilo** [comment]
Done. Closed.
