### ISSUE TITLE
Workshop [Eastern Catalyst School]: Preparation for 6th Workshop: "Last phase – How to Vote and to get Voted in Catalyst" 31 July 2022

### ISSUE THREAD

**Issue by zicozibu** [C3ETH/c3eth-operations#321]
## Preparation for 6th Workshop: "Last phase – How to Vote and to get Voted in Catalyst" 31 July 2022

**Eastern Catalyst School - Indonesia Team log line**
- [Previous Log 
](https://github.com/C3ETH/c3eth-operations/issues/307)
- [Next Log](https://github.com/C3ETH/c3eth-operations/issues/355)

**Date and time:**
- Sunday, 31 July 2022
- Time: 19:00 - 21:00 UTC+7

**Tasks:**

- [x] Meeting on Thursday, 28 July 2022 for Eastern Catalyst School Indonesia
- [x] 6th Workshop material preparation @syarbel [[PPT Link](https://docs.google.com/presentation/d/1W_7DXUicBEO80_JqttC96-_QcRNh5Q9ri4A0R5_76zI/edit?usp=sharing)] 
- [x] Create a flyer @YanTirta 
- [x] Share workshop information on social media and groups (Twitter, Discord, Telegram OK, SPO Cardanesia, SPO Kawan)
- [x] Record the event to local storage @zicozibu   
- [x] Upload workshop recording to YouTube @zicozibu YouTube [Link](https://youtu.be/EswckbVjFtk)
- [x] Create [a recap workshop](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-6-how-to-vote-in-catalyst-fund-9-recap/106202) in Cardano Indonesia Forum (screenshots, participants, etc.) @andreassosilo 

### Workshop preparation

1. Speaker: @syarbel @danivideda  
2. Moderator: Dewi Gunarto
3. Host: @zicozibu 
4. Things to cover:
    - Opening introduction -> 5 min
    - Brief updates on Fund 9 with PA, vPA -> 5 min
    - Introduction to voting in Catalyst -> 10 min
    - Video demo for registration -> 5 min
    - Q&A part 1 -> 10 min (max)
    - How to choose proposal -> 15 min
    - How reward works in voting -> 5 min
    - Proposer from Indonesia presentation (6 total) -> 40 minutes
         - Present: 5 minutes
         - Q&A: 1-2 minutes
    - Sharing session from Indonesian vPA and Q&A: Tips for voter -> 20 minutes
    - Closing -> 5 minutes

### Discussion
- New meeting time moved from 15:30 - 16:30 UTC+7 to 16:00 - 17:00 UTC+7

**Comment by zicozibu** [comment]
Recording to the event is done at Cloud, already downloaded and uploaded to:
1. Youtube at https://youtu.be/EswckbVjFtk
2. Indonesia ECS GDrive at (coming soon)

**Comment by zicozibu** [comment]
Fund 9 presenting proposals:
1. AMA with Cross-Chain Communities
https://cardano.ideascale.com/c/idea/416801/
Ivan Kwananda

2. YouTube educational video in Bahasa
https://cardano.ideascale.com/c/idea/417366
Andre Tuwan 

3. Trust & Transparent News Portal	
https://cardano.ideascale.com/c/idea/420823	
Sonny Dhamayana

4. Web ADA Info Community In Bahasa	
https://cardano.ideascale.com/c/idea/418728	
Gorga Siagian

**Comment by zicozibu** [comment]
Recap Workshop done by @andreassosilo can be found here: https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-6-how-to-vote-in-catalyst-fund-9-recap/106202
