### ISSUE TITLE
Add C3ETH Twitter Handle to Stake Pool Metadata

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#93]
**Tasks:**

- [ ] Add C3ETH Twitter handle @c3eth to the metadata.json
- [ ] Confirm with Lauris
- [ ] Final check in cardanoscan.io or in another blockchain explorer
